### ISSUE TITLE
 failed to load command: derailed | How can I fix this?

### ISSUE THREAD

**Issue by hugoh59** [schneems/derailed_benchmarks#111]
bundler: failed to load command: derailed (/usr/local/opt/rbenv/versions/2.3.3/bin/derailed)
RuntimeError: Bad request: 
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:92:in `call_app'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:252:in `block (2 levels) in <top (required)>'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/derailed_benchmarks-1.3.2/bin/derailed:41:in `exec'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/derailed_benchmarks-1.3.2/bin/derailed:92:in `<top (required)>'
  /usr/local/opt/rbenv/versions/2.3.3/bin/derailed:23:in `load'
  /usr/local/opt/rbenv/versions/2.3.3/bin/derailed:23:in `<top (required)>'

**Comment by yjukaku** [comment]
Just ran into this issue - this isn't a very good error message. You'll see `Bad request` written there, which is the useful part: Your page probably returned `401 Unauthorized` or something similar. You might need to set headers using ENV vars as described in the README.

**Comment by schneems** [comment]
Try https://github.com/schneems/derailed_benchmarks#running-in-production-locally for help debugging locally
