### ISSUE TITLE
IPS_WARMUP and IPS_TIME configuration

### ISSUE THREAD

**Issue by yjukaku** [schneems/derailed_benchmarks#115]
Hey @schneems thanks for your work on this gem!

Would you accept a PR for being able to specify the `Benchmark.ips` `:config` and `:time` options? As of now the `perf:ips` task is not useful if the endpoint you are hitting is very slow (over ~1 second) since the default `:time` of 5 seconds is not enough to eliminate noise.  The proposed API would be

```
IPS_WARMUP=5 IPS_TIME=30 derailed exec perf:ips
```

**Comment by schneems** [comment]
Just merged a similar feature into master. Sorry I missed this when it came in
