### ISSUE TITLE
Add "subdomain" option for mem_over_time task

### ISSUE THREAD

**Issue by dannysullivan** [schneems/derailed_benchmarks#124]
I am working on diagnosing a memory leak in an app that uses a subdomain architecture.  In order to use derailed's mem_over_time task, I needed to manually edit one of the files in the gem that contains a hardcoded reference to `http://localhost`.  It would be nice if there were a `SUBDOMAIN` option, similar to the `PATH_TO_HIT` option, that allowed users to optionally supply a subdomain to hit.

**Comment by schneems** [comment]
It looks like subdomains can already be specified by giving path to hit a full URL:

```
$ PATH_TO_HIT=http://subdomain.lvh.me:3000/users/new bundle exec derailed exec perf:mem
```
