### ISSUE TITLE
Problem with detecting rack application

### ISSUE THREAD

**Issue by wafcio** [schneems/derailed_benchmarks#133]
`derailed_benchmarks` detects rails/rack application by `railtie` gem. It isn't completely good option because some gem which can be used in rack application require `railtie`.

For example `standalone_migrations` gem requires `railtie`. So whenever it is used in rack (non-Rails) app then rails setup is invoked instead of rack setup.

I think it will be good to prepare a mechanism which will force in this moment rack setup somehow.

**Comment by schneems** [comment]
I'm open to work in this space but it's not on my roadmap for implementation anytime soon.

**Comment by schneems** [comment]
On second read i'm not totally sure what the ask is here. If you're experiencing faulty behavior or something that you need that is not possible at this time please open a new issue.
