### ISSUE TITLE
perf:ram_over_time is stopping after couple of times

### ISSUE THREAD

**Issue by onemanstartup** [schneems/derailed_benchmarks#14]
`RAILS_ENV=production SKIP_FILE_WRITE=true rake -f perf.rake perf:ram_over_time TEST_COUNT=20`
Doesn't matter what settings i changing it is silently stops.

**Comment by schneems** [comment]
You'll need to check your local logs to see why it is failing. 

```
$ tail -f logs/production.log
```

Then run the script in another tab.

**Comment by onemanstartup** [comment]
Damn I'm an idiot :) Thank you.

**Comment by onemanstartup** [comment]
Damn I'm twice an idiot. First time in evening, second on morning.
Actually there is no errors in logs, only requests.
```
RAILS_ENV=production rake -f perf.rake perf:ram_over_time                                            
Booting: production
PID: 47478
96.53515625
109.953125
110.4453125
```
When error it crashes with `See full trace by running task with --trace` but it gracefully shutdown, or so it seems.

**Comment by schneems** [comment]
`TEST_COUNT=20` is really low. The task is probably done. It only outputs a metric every 5 seconds.

**Comment by onemanstartup** [comment]
Yes. Sorry for taking your time.  It works, I thought it will be testing constantly. Thank you.
