### ISSUE TITLE
Error in 1.3.x - heapy requires Ruby 2.3+

### ISSUE THREAD

**Issue by kboyd31** [schneems/derailed_benchmarks#146]
The requirements on this project say Ruby 2.1+ but when trying to install this on our 2.2 Ruby system, we are getting the following error:

Gem::RuntimeRequirementNotMetError: heapy requires Ruby version ~> 2.3. The current ruby version is 2.2.0.
An error occurred while installing heapy (0.1.4), and Bundler cannot continue.
Make sure that `gem install heapy -v '0.1.4' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  derailed_benchmarks was resolved to 1.3.6, which depends on
    heapy

Is there a work around for this? Or Does the documentation need to be updated?

**Comment by schneems** [comment]
It looks like the version of heapy that makes that requirement has never been released https://rubygems.org/gems/heapy/versions/0.1.4 (does not have a Ruby version requirement).

Alternatively, you could try with heapy 0.1.3 which was before https://github.com/schneems/heapy/commit/4f8ec3577ea3c7a6b62703dc8748e067c4133e45#diff-a281e47da81fd62c693f17d21f2bd271

I would say we should update the docs as even Ruby 2.3 is already EOL.

**Comment by kboyd31** [comment]
Thanks for the reply, I will give that a try. We will eventually be moving to a higher version of Ruby, but we are so far behind right now we gotta deal with what have :) Wanted to run some benchmarks, so hopefully this helps!

**Comment by schneems** [comment]
Were you able to get this to work with heapy 0.1.3? We could also remove it as a hard dependency of derailed and instead raise an error only when someone is trying to use a feature that requires heapy (if it isn't found, while raising a helpful error).
