### ISSUE TITLE
Ruby 2.1 and 2.2 don't have support for frozen string literals

### ISSUE THREAD

**Issue by elfotografo007** [schneems/derailed_benchmarks#171]
The README and gemspec list this gem as compatible with ruby 2.1+. However, the frozen string literals syntax was introduced in ruby 2.3. Therefore, and error is raised when used in ruby 2.2.

Details of the error:

derailed_benchmarks-1.6.0/lib/derailed_benchmarks/require_tree.rb:43:in `to_string': undefined method `+@' for "TOP: 145.7539 MiB":String (NoMethodError)

Ruby version: 2.2.2
Gem version: 1.6.0.

**Comment by schneems** [comment]
That's a bug then, we can switch to `String.new` instead of `+"` if anyone wants to send a PR. Also we should probably move testing to circle ci and add Ruby 2.2 in our matrix

**Comment by schneems** [comment]
Fixed in 1.8.x
