### ISSUE TITLE
I don't have the report but I get 'coplex_starter_backend_development' already exists

### ISSUE THREAD

**Issue by rhtaylor** [schneems/derailed_benchmarks#197]
I attempted to run the command TEST_COUNT=20_000 bundle exec derailed exec perf:mem_over_time and I get the error
``` 
Database 'coplex_starter_backend_development' already exists
Endpoint: "/"
PID: 2015
Couldn't call app. Bad request to /! Resulted in 301 status. 

``` 
I ran this command before and the output was incomplete due to a bad database table and did not actually run. I fixed the database issue and I cannot rerun the command. What can I do to correct this? Can I delete some files? Can I reset something?

**Comment by schneems** [comment]
I have instructions for debugging booting locally here https://github.com/schneems/derailed_benchmarks#running-in-production-locally. I've not hit this problem personally as you're describing.

My suggestion would be to either try to follow the stack trace to see why/what is trying to create a database and then remediate that. Alternatively start with a new "clean" rails app try to add code into it to replicate your existing rails app until it starts to fail in the same way (when this happens, you'll know you've found the problem).
