### ISSUE TITLE
perf:require_bench not working as expected

### ISSUE THREAD

**Issue by lacco** [schneems/derailed_benchmarks#22]
I just read your great post on http://www.schneems.com/2014/11/07/i-ram-what-i-ram.html , and had to do two tweaks to get ```bundle exec rake -f perf.rake perf:require_bench``` to work as expected (using ```derailed_benchmarks``` master):

1. ```perf:require_bench``` loads ```derailed_benchmarks/core_ext/kernel_require.rb``` after the setup task is executed. This way I don't get measures for the requires that are called during bootup. My solution: Require this file in ```perf.rake```.

2. With ```CUT_OFF != 0```, I never got any output since the ```TOP_REQUIRE``` node always has a zero cost. My workaround is to check for ```name != "TOP" ``` in https://github.com/schneems/derailed_benchmarks/blob/master/lib/derailed_benchmarks/require_tree.rb#L37

I am not absolutely sure how to fix those two issues, but I at least wanted to report them as others might stumple upon similar things.

Thank you for your great work!

**Comment by schneems** [comment]
> This way I don't get measures for the requires that are called during bootup.

This is exactly what this code was designed to do, measure requires during bootup. Maybe you can explain some more about why you want this.

If you are going to only profile one require, maybe check out https://github.com/Locke23rus/require_prof

**Comment by lacco** [comment]
>> This way I don't get measures for the requires that are called during bootup.

> This is exactly what this code was designed to do, measure requires during bootup. Maybe you can explain some more about why you want this.

I wanted to find out which gems are causing my rails app requiring about 250 Mb after startup. In an earlier version of ```derailed_benchmarks```, I found the following line (https://github.com/schneems/derailed_benchmarks/blob/2aa82a640939d6a1818db1327d1f577b19e3face/lib/derailed_benchmarks/tasks.rb#L190): 

```ruby
task :require_bench => [:kernel_require_patch , :setup] do
````

Currently, the task looks like this:

```ruby
task :require_bench => [:setup] do
  require 'derailed_benchmarks/core_ext/kernel_require.rb'
```

As far as I understand this change, previously ```require``` has been patched before the application boot, and now it is patched after the application has been started. That is why I didn't got the expected memory  statistics.

**Comment by schneems** [comment]
That was a mistake on my part, thanks for reporting.

**Comment by lacco** [comment]
Thank you vey much, this fixes the first issue! 

Just as a reminder, I had a second issue with the code: ```TOP_REQUIRE.print_sorted_children``` always printed nothing for ```CUT_OFF != 0``` since the cost of ```TOP_REQUIRE``` is always ```0```.

**Comment by schneems** [comment]
I understand now. I think we should do something like this:

```ruby
TOP. sorted_children.each {|c| c. print_sorted_children }
```

We should probably add tests for these cases.

**Comment by simonnordberg** [comment]
Great to find that this issue was already taken care of, I was just about to submit an issue+PR. Thanks!
