### ISSUE TITLE
Getting NoMethodError: undefined method `initialized?' error when running perf:require_bench

### ISSUE THREAD

**Issue by neelbhat88** [schneems/derailed_benchmarks#24]
I'm running a Rails 3.2.19 app and when I run the perf:require_benchmarks I get the following. It works fine on a Rails 4 app though:

neel@Neels-MacBook-Pro:~/railsapps/imua$ bundle exec rake -f perf.rake perf:require_bench --trace
Your Gemfile lists the gem rspec-rails (~> 3.0.0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem factory_girl_rails (~> 4.0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem jasmine (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
** Invoke perf:require_bench (first_time)
** Invoke perf:kernel_require_patch (first_time)
** Execute perf:kernel_require_patch
** Invoke perf:setup (first_time)
** Execute perf:setup
rake aborted!
NoMethodError: undefined method initialized?' for #<Imua::Application:0x007fe5a2bf4e30>
/Users/neel/.rvm/gems/ruby-2.1.2/gems/derailed_benchmarks-0.0.0/lib/derailed_benchmarks/tasks.rb:29:inblock (2 levels) in '
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in call'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:inblock in execute'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in each'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:inexecute'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:179:in block in invoke_with_call_chain'
/Users/neel/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:inmon_synchronize'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:172:in invoke_with_call_chain'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:201:inblock in invoke_prerequisites'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:199:in each'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:199:ininvoke_prerequisites'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:178:in block in invoke_with_call_chain'
/Users/neel/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:inmon_synchronize'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:172:in invoke_with_call_chain'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:165:ininvoke'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:150:in invoke_task'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:inblock (2 levels) in top_level'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in each'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:inblock in top_level'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:115:in run_with_threads'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:100:intop_level'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:78:in block in run'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:176:instandard_exception_handling'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:75:in run'
/Users/neel/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/bin/rake:33:in'
/Users/neel/.rvm/gems/ruby-2.1.2/bin/rake:23:in load'
/Users/neel/.rvm/gems/ruby-2.1.2/bin/rake:23:in'
Tasks: TOP => perf:require_bench => perf:setup

I'm really excited to use this library but hopefully it's compatible with Rails 3.2.19..

**Comment by EddM** [comment]
It looks like the version at rubygems isn't up-to-date. Try installing the gem straight from github:

`gem 'derailed_benchmarks', git: "git@github.com:schneems/derailed_benchmarks.git"`

**Comment by cllns** [comment]
I ran into the same issue, and adding the github source fixed it! 

@schneems, do you mind you releasing a new version to rubygems to fix this?

**Comment by schneems** [comment]
There's still one issue I want to fix before a release

**Comment by schneems** [comment]
I released v1.0.0 today, check out the readme. I added a `$ derailed` command, and you no longer need to boot your whole app just to see how much memory dependencies are using.
