### ISSUE TITLE
Command not found: derailed

### ISSUE THREAD

**Issue by chrisccerami** [schneems/derailed_benchmarks#29]
The Gemfile:
https://gist.github.com/chrisccerami/dd5233cfccd67a2a4505

Bundle list:
Gems included by the bundle:
  * actionmailer (4.0.0)
  * actionpack (4.0.0)
  * activeadmin (0.6.1 1f4f90c)
  * activemodel (4.0.0)
  * activerecord (4.0.0)
  * activerecord-deprecated_finders (1.0.3)
  * activesupport (4.0.0)
  * addressable (2.3.5)
  * akismetor (1.0.0)
  * arbre (1.0.1)
  * arel (4.0.0)
  * atomic (1.1.13)
  * axiom-types (0.0.5)
  * bcrypt-ruby (3.1.2)
  * benchmark-ips (2.2.0)
  * better_errors (1.0.1)
  * binding_of_caller (0.7.2)
  * bourbon (3.1.8)
  * browser (0.8.0)
  * builder (3.1.4)
  * bundler (1.7.7)
  * capybara (2.1.0)
  * capybara-webkit (1.0.0)
  * celluloid (0.15.2)
  * ckeditor (4.0.6)
  * climate_control (0.0.3)
  * cocaine (0.5.1)
  * coderay (1.0.9)
  * coercible (1.0.0)
  * coffee-rails (4.0.0)
  * coffee-script (2.2.0)
  * coffee-script-source (1.6.3)
  * debug_inspector (0.0.2)
  * derailed (0.1.0)
  * derailed_benchmarks (0.0.0)
  * descendants_tracker (0.0.3)
  * devise (3.1.0)
  * diff-lcs (1.2.4)
  * dotenv (1.0.2)
  * dotenv-rails (1.0.2)
  * equalizer (0.0.9)
  * erubis (2.7.0)
  * excon (0.25.3)
  * execjs (2.0.0)
  * factory_girl (4.2.0)
  * factory_girl_rails (4.2.1)
  * faraday (0.8.8)
  * ffi (1.9.3)
  * fog (1.15.0)
  * formatador (0.2.4)
  * formtastic (2.3.0.rc2)
  * geocoder (1.1.8)
  * get_process_mem (0.2.0)
  * guard (2.2.5)
  * guard-rspec (4.2.3)
  * has_scope (0.6.0.rc)
  * hashie (2.0.5)
  * hike (1.2.3)
  * httpauth (0.2.0)
  * i18n (0.6.5)
  * ice_nine (0.11.0)
  * inherited_resources (1.4.1)
  * jquery-rails (3.0.4)
  * jquery-ui-rails (4.0.5)
  * json (1.8.0)
  * jwt (0.1.8)
  * kaminari (0.14.1)
  * kgio (2.8.1)
  * launchy (2.3.0)
  * listen (2.4.0)
  * lumberjack (1.0.4)
  * mail (2.5.4)
  * memory_profiler (0.9.0)
  * method_source (0.8.2)
  * mime-types (1.24)
  * mini_portile (0.5.1)
  * minitest (4.7.5)
  * multi_json (1.7.9)
  * multipart-post (1.2.0)
  * net-scp (1.1.2)
  * net-ssh (2.7.0)
  * newrelic_rpm (3.6.9.171)
  * nokogiri (1.6.0)
  * oauth (0.4.7)
  * oauth2 (0.8.1)
  * omniauth (1.1.4)
  * omniauth-facebook (1.4.1)
  * omniauth-oauth (1.0.1)
  * omniauth-oauth2 (1.1.1)
  * omniauth-twitter (1.0.0)
  * orm_adapter (0.4.0)
  * paperclip (3.5.1)
  * pg (0.16.0)
  * polyamorous (0.6.4)
  * polyglot (0.3.3)
  * pry (0.9.12.2)
  * pry-nav (0.2.3)
  * quiet_assets (1.0.2)
  * rack (1.5.2)
  * rack-test (0.6.2)
  * rails (4.0.0)
  * rails_12factor (0.0.2)
  * rails_serve_static_assets (0.0.1)
  * rails_stdout_logging (0.0.1)
  * railties (4.0.0)
  * raindrops (0.12.0)
  * rake (10.1.0)
  * ransack (1.0.0)
  * rb-fsevent (0.9.4)
  * rb-inotify (0.9.3)
  * rdoc (3.12.2)
  * responders (1.0.0)
  * rspec (2.14.1)
  * rspec-core (2.14.5)
  * rspec-expectations (2.14.2)
  * rspec-mocks (2.14.3)
  * rspec-rails (2.14.0)
  * ruby-hmac (0.4.0)
  * sass (3.2.10)
  * sass-rails (4.0.0)
  * sdoc (0.3.20)
  * shoulda-matchers (2.3.0)
  * simple_form (1.4.1)
  * slop (3.4.6)
  * sprockets (2.10.0)
  * sprockets-rails (2.0.0)
  * textacular (3.1.0)
  * thor (0.18.1)
  * thread_safe (0.1.2)
  * tilt (1.4.1)
  * timecop (0.6.3)
  * timers (1.1.0)
  * treetop (1.4.15)
  * tzinfo (0.3.37)
  * uglifier (2.2.0)
  * unicorn (4.7.0)
  * virtus (1.0.1)
  * warden (1.2.3)
  * webshims-rails (1.11.6.1)
  * wepay (0.0.3 43a98d4)
  * xpath (2.0.0)
  * zonebie (0.5.1)

It appears as though derailed_benchmarks (0.0.0) is being installed rather than derailed_benchmarks (1.0.0) like in other apps. When setting derailed_benchmarks explicitly to 1.0.0 in my Gemfile, I received the following:

```
Bundler could not find compatible versions for gem "rake":
  In Gemfile:
    derailed_benchmarks (~> 1.0.0) ruby depends on
      rake (~> 10.4) ruby

    sass-rails (~> 4.0.0) ruby depends on
      railties (< 5.0, >= 4.0.0.beta) ruby depends on
        rake (10.1.0)
```

**Comment by schneems** [comment]
We can probably relax the dependency on Rake to "~> 10" https://github.com/schneems/derailed_benchmarks/blob/82fdee5150f303414bf85d711fc0db8a646746c2/derailed_benchmarks.gemspec#L25 can you give me a PR that does that?

**Comment by chrisccerami** [comment]
:+1:

**Comment by chrisccerami** [comment]
#30 submitted

**Comment by chrisccerami** [comment]
#30 seems to have resolved the issue. Everything's working smoothly now.

**Comment by schneems** [comment]
Awesome, going to close this for now, thanks for the report and the fix!
