### ISSUE TITLE
Subdomain support in `PATH_TO_HIT`?

### ISSUE THREAD

**Issue by hale** [schneems/derailed_benchmarks#34]
Thanks for the library - I think this is the best out there for diagnosing memory issues...

Question: running against a real webserver, it looks like adding support for subdomains is possible - as we're just sub-shelling out to curl.  But what about Rack::Mock?  Is it possible to use subdomains in the endpoint in this case?

Thanks again!

**Comment by schneems** [comment]
This is how Rack::Mock parses the `opts` you pass to it https://github.com/rack/rack/blob/99293fa13d86cd48021630fcc4bd5acc9de5bdc3/lib/rack/mock.rb#L88-L150

It doesn't look like there's specific support for subdomain, however any key you pass in there gets merged into the Rack `env` object. So the first step would be to get a rack env object when we are using a subdomain. From there we can figure out the key, and we could pretty easily add subdomains support. Do you have an app that handles subdomains locally? Can you look into getting a rack env for me?

**Comment by hale** [comment]
Here's a request env hash: https://gist.github.com/hale/0bca572ffaf9f22f6e68

----

Sorry I should have just tried....think this issue can be closed!

I can pass a full URL - like `PATH_TO_HIT="http://lvh.me:3000/admin/posts/" derailed exec perf:ram_over_time` - and the subdomain is picked up, as you'd expect given https://github.com/rack/rack/blob/99293fa13d86cd48021630fcc4bd5acc9de5bdc3/lib/rack/mock.rb#L95

By the way, do you know if using `lvh.me` means connecting to the network each time, or is there some kind of DNS caching going on...?

**Comment by caifara** [comment]
It would be helpful to explain in the readme that a full uri can be used in the PATH_TO_HIT (making it possible to hit a subdomain endpoint) but not in combination with USE_SERVER.

**Comment by schneems** [comment]
Sure, want to send a doc PR. You could link to this issue.

**Comment by gotoAndBliss** [comment]
I'm trying to use a full URL but it seems to be appending it to the end of local host like so..

    USE_SERVER=pow PATH_TO_HIT=http://love.whisper.dev bundle exec derailed exec perf:mem_over_time

Which returns..

    /Users/peanut_butter/.rvm/gems/ruby-2.1.5@whisper/ruby/2.1.0/gems/derailed_benchmarks-1.3.1/lib/derailed_benchmarks/tasks.rb:85:in `call_app': Bad request to "curl 'http://localhost:3056/http://love.whisper.dev' -s --fail 2>&1" Response: (RuntimeError)

**Comment by schneems** [comment]
That's expected https://github.com/schneems/derailed_benchmarks/blob/10e1f7d5fb4bae5f5b12aa0d9fab936c098934b8/lib/derailed_benchmarks/tasks.rb#L82-L95

This was mentioned on Mar 16th

> in the PATH_TO_HIT (making it possible to hit a subdomain endpoint) but not in combination with USE_SERVER.

And was documented in https://github.com/schneems/derailed_benchmarks/pull/76/files which is attached to this issue, mentioned in the README, and is the link right above your comment.

![](https://www.dropbox.com/s/th5q5xqfd6qfl7g/Screenshot%202016-06-09%2009.44.13.png?dl=1)

We should probably introduce a `URL_TO_HIT` that requires full URL instead of just the path.

Does pow work for a server?

**Comment by gotoAndBliss** [comment]
Ah that'd be cool. I should have read the README more thoroughly.

Also yes, POW seems to work.
