### ISSUE TITLE
Warning before benchmarks

### ISSUE THREAD

**Issue by rogeriozambon** [schneems/derailed_benchmarks#37]
This isn't a problem. Whenever I run the command `derailed bundle:mem`, for example, a warning is displayed:

``` ruby
WARN: Unresolved specs during Gem::Specification.reset:
      rack (~> 1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```

However, running the same command with `bundle exec`, this warning is no longer displayed. I understand what it is. If you think this relevant, we can adjust it.

Thanks, Richard.
Best!

**Comment by schneems** [comment]
> we can adjust it.

How do you propose to get rid of the error message?

**Comment by monkbroc** [comment]
You can either use `bundle exec` as you say or you can create a binstub for derailed with `bundle binstubs derailed_benchmarks`. The warning won't be shown anymore with `bin/derailed bundle:mem`.

The other thing to try is `gem cleanup <name of gem in warning>` if you don't need the old versions. If versions you actually need end up being uninstalled, you can always do `bundle install`.

**Comment by schneems** [comment]
Lets update the docs if there's any calls that don't have `bundle exec` that seems like the most reasonable way forward. Either of you up for some doc PRs?
