### ISSUE TITLE
Error when running derailed exec perf:ram_over_time

### ISSUE THREAD

**Issue by cmalpeli** [schneems/derailed_benchmarks#38]
I'm running the following command: 
TEST_COUNT=50_000 derailed exec perf:ram_over_time

The name of my rails app is "job_board"

Which results in the following errors:
booting: production
Digest::Digest is deprecated; use Digest
job_board already exists
Endpoint: "/"
{my-local-path}/derailed_benchmarks/tasks.rb:72: warning: already initialized constant DERAILED_APP
{my-local-path}/derailed_benchmarks-1.0.1/lib/derailed_benchmarks/tasks.rb:23: warning: previous definition of DERAILED_APP was here
PID: 11839
152.453125
{my-local-path}/derailed_benchmarks-1.0.1/lib/derailed_benchmarks/tasks.rb:92:in `call_app': Bad request:  (RuntimeError)

Any thoughts as to what is happening here?

**Comment by schneems** [comment]
You'll need to look at your logs to see what is failing. Make sure to go through the steps listed in https://github.com/schneems/derailed_benchmarks#running-in-production-locally

**Comment by mberman84** [comment]
I'm having this same issue even though I'm able to boot up console and server production

**Comment by schneems** [comment]
@mberman84 you'll need to look in your logs to get an error message

```
$ tail -f log/production.log
```

I'm interested in maybe doing a project where we self pipe that data into the derailed output on failure, or something. I haven't thought enough about it, but i'm interested in the area.

**Comment by AaronCowan** [comment]
I was having a very similar issue to this and the solution was to specify the server I was using. In my case I was using Puma. So, I had to run USE_SERVER=puma before the command.

**Comment by jerhinesmith** [comment]
Thanks @AaronCowan - that fixed the issue for me as well.

**Comment by obromios** [comment]
👍

**Comment by dlamichhane** [comment]
धन्यवाद - Thank you!
