### ISSUE TITLE
Consider adding option to ignore database

### ISSUE THREAD

**Issue by monfresh** [schneems/derailed_benchmarks#39]
Thanks for this awesome gem! I used it to track down a gem that consumed a lot of memory, and submitted a pull request that eliminated the problem.

In a separate app that doesn't use a database, I just tried running `derailed exec perf:mem`, and it complained that it `could not load database configuration. No such file - ["config/database.yml"]`. Maybe I missed it, but I couldn't find a way to specify that my app doesn't use a database.

**Comment by schneems** [comment]
You need to remove ActiveRecord from your gemfile, that's how we detect if you're using a database or not: https://github.com/schneems/derailed_benchmarks/blob/4f52be88500d97638c4c4121daae14237edcce3e/lib/derailed_benchmarks/tasks.rb#L31-L41

**Comment by monfresh** [comment]
I don't think that's a safe assumption to make.  I don't specifically have `activerecord` in my [Gemfile](https://github.com/monfresh/ohana-sms/blob/master/Gemfile), but I do have `rails`, and therefore my Gemfile.lock will have everything that rails depends on, including `activerecord`.

Just because I have `activerecord` in my Gemfile.lock doesn't mean I have a database. I'm not requiring it in [application.rb](https://github.com/monfresh/ohana-sms/blob/master/config/application.rb#L8) and I don't make use of it.

I think there are better ways to determine if a Rails app is using a database, such as looking for `database.yml` or `schema.rb` or `structure.sql` or `db/migrate`, or database-related gems such as `sqlite3`, `mysql`, `pg`, etc.

**Comment by schneems** [comment]
Most of those won't work. The ones that do work could just as still trigger false positives.




The interface is gem inclusion. I'll take a doc PR to call out to people how to skip the migration stuff if you want to write that up.




To avoid active record, use railties in your Gemfile instead of rails.



—

**Comment by ashrestha91** [comment]
In my situation, unfortunately, another gem is requiring rails, so I can't pick around ActiveRecord (I am using the other rails components).  

What's the reason against a manual override flag?  I did try to run it after manually removing those lines of code from the tasks.rb, without success. It looks like something else added ActiveRecord to the config.eager_load_namespaces.

**Comment by schneems** [comment]
If another gem depends on rails and not ralties then that is a bug if it isn't use active record. The thing to do would be to fork the gem, change the gem spec and submit a PR. You can run against your fork in production while you're waiting.

If it's in your Gemfile.lock rails will load it at boot.

**Comment by jeremyhaile** [comment]
We are hitting this issue as well. We use rails but not activerecord. 3 of the gems we use have a dependency on rails, not railties.

Rails recommends not including in application.rb to disable activerecord.

Huge pain to have to workaround. It would be much easier if we could just pass a flag to disable activerecord testing.

**Comment by jeremyhaile** [comment]
@schneems after following your suggestion to remove rails and replace it with railties, I know get this error: `cannot load such file -- action_mailer/railtie`

**Comment by schneems** [comment]
I don't mind adding an env var flag to skip the active record stuff since it is such a huge pain if someone wants to give me a PR for that. I'm thinking `DERAILED_SKIP_ACTIVE_RECORD=true` you could set it in your `perf.rake` file once (`ENV["DERAILED_SKIP_ACTIVE_RECORD"] = "true"`) and not have to remember it.

**Comment by ashrestha91** [comment]
Cool, I made a PR for it in #60 
Wasn't sure where to document it though
