### ISSUE TITLE
Bad request when executing require_bench

### ISSUE THREAD

**Issue by isc** [schneems/derailed_benchmarks#5]
Hi,

The require_bench rake task fails with a bad request error. What can I do to troubleshoot this ?

```
 bundle exec rake -f perf.rake perf:require_bench --trace
** Invoke perf:require_bench (first_time)
** Invoke perf:kernel_require_patch (first_time)
** Execute perf:kernel_require_patch
** Invoke perf:setup (first_time)
** Execute perf:setup
Booting: production
** Execute perf:require_bench
## Impact of `require <file>` on RAM

Showing all `require <file>` calls that consume 0.3 mb or more of RSS
Configure with `CUT_OFF=0` for all entries or `CUT_OFF=5` for few entries
Note: Files only count against RAM on their first load.
      If multiple libraries require the same file, then
       the 'cost' only shows up under the first library

rake aborted!
Bad request: 
/Users/ivan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/derailed_benchmarks-0.0.0/lib/derailed_benchmarks/tasks.rb:56:in `call_app'
/Users/ivan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/derailed_benchmarks-0.0.0/lib/derailed_benchmarks/tasks.rb:177:in `block (2 levels) in <top (required)>'
/Users/ivan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
```

**Comment by xsannyx** [comment]
What is the status of this issue? I'm having the same problem even if I set the PATH_TO_HIT to a path that returns a 200 success response.

**Comment by schneems** [comment]
For debugging you can tail your production logs. It would be nice if I did something fancy like captured ruby logs from STDOUT and displayed them when there's an error. There's no ETA on such a feature though.

**Comment by schneems** [comment]
Check out the readme, I added a more tutorial-y style walkthrough. Also you can now run some commands without needing to boot your app. 

Would still like to do a STDOUT log capture and emit errors on failure, but haven't yet. It's on my radar

**Comment by schneems** [comment]
Closing this in favor of https://github.com/schneems/derailed_benchmarks/issues/27, though you should be able to run this command with `$ derailed bundle:mem` now without booting your app.
