### ISSUE TITLE
Authentication protected app issue

### ISSUE THREAD

**Issue by MaartenG** [schneems/derailed_benchmarks#6]
I have an application where the root path is a page with omniauth-crowd authentication. Because of this, call_app fails with 

```
Bad request: <html><body>You are being <a href="http://example.org/auth/crowd/">redirected</a>.</body></html>
```

Should it really consider a redirect a failure?

**Comment by schneems** [comment]
You can now perform some benchmarking without having to boot your app. Check the readme for more info. I still haven't addressed this specific issue. Not 100% sure the best way to move forwards

**Comment by schneems** [comment]
You can test with an authenticated endpoint now.
