### ISSUE TITLE
Allocated Memory Changes

### ISSUE THREAD

**Issue by ems2141** [schneems/derailed_benchmarks#62]
Hello,

This code is working perfectly with our application but we are seeing some seemingly alarming results that I wanted to inquire about.  

When I run: 
`bundle exec derailed exec perf:objects`
as well as:
`TEST_COUNT=10 bundle exec derailed exec perf:objects`

I see our allocated memory increase by a multiple of 10.  Is this normal behavior?  

Here is a sample of the output I see for TEST_COUNT=1: 
## allocated memory by gem

   3604658  haml-4.0.5
   1921843  activerecord-4.1.6
   1879824  parslet-1.6.0
   1749971  activesupport-4.1.6
    737334  activejunky2/app
    448577  rack-1.5.5
    392121  other
    196629  arel-5.0.1.20140414130214
    169070  newrelic_rpm-3.12.1.298
    131902  actionpack-4.1.6
    120986  actionview-4.1.6
    118832  thread_safe-0.3.5
    108375  dalli-2.7.2
     96825  pg-0.17.1
     49667  2.2.1/lib
     17208  warden-1.2.3
     15536  activejunky2/lib
     13600  active_hash-1.4.0
     12976  activemodel-4.1.6
      7258  devise-3.4.0
      3225  shortcode-1.0.0
      2241  railties-4.1.6
      2059  omniauth-1.2.2
      1993  json-1.8.3
      1920  hashie-3.4.3
      1688  css_splitter-0.4.1
      1040  sprockets-rails-2.3.3
       368  tzinfo-1.2.2
       288  sentry-raven-0.13.3
       240  sunspot_rails-2.1.1
       200  sprockets-2.11.0
       167  sunspot-2.1.1

and here is for TEST_COUNT=10:
## allocated memory by gem

  36009140  haml-4.0.5
  19218430  activerecord-4.1.6
  18794640  parslet-1.6.0
  17497676  activesupport-4.1.6
   7373340  activejunky2/app
   4485770  rack-1.5.5
   3921210  other
   1966290  arel-5.0.1.20140414130214
   1691701  newrelic_rpm-3.12.1.298
   1318660  actionpack-4.1.6
   1200761  actionview-4.1.6
   1188320  thread_safe-0.3.5
   1075010  dalli-2.7.2
    968250  pg-0.17.1
    496670  2.2.1/lib
    172080  warden-1.2.3
    155360  activejunky2/lib
    136000  active_hash-1.4.0
    129760  activemodel-4.1.6
     72580  devise-3.4.0
     32250  shortcode-1.0.0
     22410  railties-4.1.6
     20590  omniauth-1.2.2
     19930  json-1.8.3
     19200  hashie-3.4.3
     16880  css_splitter-0.4.1
     10400  sprockets-rails-2.3.3
      3680  tzinfo-1.2.2
      2880  sentry-raven-0.13.3
      2400  sunspot_rails-2.1.1
      2000  sprockets-2.11.0
      1670  sunspot-2.1.1

Any feedback you are able to provide would be GREATLY appreciated.

Many thanks,
Ellie

**Comment by schneems** [comment]
> I see our allocated memory increase by a multiple of 10. Is this normal behavior?

This is relatively normal however that word "normal" is pretty loaded. I'll explain what I think is going on. This task tracks allocated objects. If 1 request needed 100 objects to perform it's job, you would expect 10 requests to need 1000 objects to work. I added the ability to run the same request multiple times to see if the objects under the "retained" header of the output grow. If that was happening it might be an indication that you've got a memory leak. 

Sometimes a first request might also set a cache or something along those lines and subsequent requests might use the cache, if you were doing this you would expect that 10 requests would be a less than 10x increase in objects, but maybe not across the board. It looks like that's not the case here and we see a 1 to 1 relationship between objects and requests.

I've spent many hours staring at the output of that command, i'll give you a quick rundown of things that jump out at me:

Looking at that output Haml is your top offender. You might want to look into upgrading to 4.0.7 https://github.com/haml/haml/blob/master/CHANGELOG.md#407 looks like there's some speed improvements. The notes for 5.0 explicitly call out memory improvements, so stay on the lookout for when that is released and try upgrading. ActiveRecord is usually pretty large, I recommend something like the `bullet` gem to see if you've got queries you aren't using or something like an `includes()` call that you don't need. Parselet is odd to be on the top. Is your app directly using it? Parsing things is pretty expensive, if you can get around it I would recommend either maybe pre-generating output or caching if possible. Looks like you're on Ruby 2.2.1, the latest 2.2.3 has some bug fixes though that probably won't affect memory use. There are some other gems in there that could bare to be upgraded, but i'm not aware of any of them being problem areas.

I really like the section "allocated memory by location" that will show you exactly what line is allocating the most memory use. It's not always directly clear how your app is triggering that use, but it's a good starting point. You can also use these environment variables to either zoom into or ignore a certain library in the output https://github.com/schneems/derailed_benchmarks/blob/4c3183eb72d62eeba0fc4288eb4351973d51f18d/lib/derailed_benchmarks/tasks.rb#L257-L258. Another good spot to look at is the top Class count. I would expect strings and hashes and maybe some internal ActiveRecord and Ruby::VM classes to be on top. After that look for classes that you defined like User, see if the number allocated makes sense in the context of the page that is being rendered.

My final piece of advice would be to make sure you're benchmarking with some "real" data. For example if you're on Heroku you can use `$ heroku pg:pull DATABASE_URL <my_local_app_production_database>`. If you do something in a view like loop over all the users returned and build some string for each of them, then it will only be representative of your production performance if you're loading users. Running these commands against empty databases can be interesting sometimes but often misleading. 

Thanks for trying out derailed. Let me know if you've got some follow up questions.

**Comment by ems2141** [comment]
Wow, you are so nice to really take the time to dig into our issue!  Going to digest everything and be in touch
