### ISSUE TITLE
ignoring TEST_COUNT ?

### ISSUE THREAD

**Issue by lbalceda** [schneems/derailed_benchmarks#63]
i'm trying to use `TEST_COUNT` param and it seems to be ending way earlier than 100 or even 1000 tries

```
TEST_COUNT=1000 USE_SERVER=puma USE_AUTH=true PATH_TO_HIT=/api/v1/notifications.json RAILS_ENV=staging derailed exec perf:mem_over_time
Booting: staging
db_development already exists
Endpoint: "/api/v1/notifications.json"
Auth: true
Port: 3419
Server: "puma"
Puma 2.15.3 starting...
* Min threads: 0, max threads: 16
* Environment: none
* Listening on tcp://0.0.0.0:3419
PID: 52447
196.63671875
203.9296875
204.78515625
205.76953125
206.046875
206.07421875
206.2109375
206.29296875
206.41796875
206.51171875
206.6328125
206.64453125

#kicked out to shell here
```

there were no errors in my log, just regular hits to the server ( i set log level to debug as well ). are there any other debug flags I could set to try to figre out why its stopping early?

**Comment by alosada** [comment]
I have a similar issue, getting kicked to shell after first test...

**Comment by schneems** [comment]
The output of `perf:mem_over_time` is every 5 seconds regardless of how many requests your app has processed. Can your server handle 1000 requests in 60 seconds?

I also recommend not using a `RAILS_ENV=staging` https://devcenter.heroku.com/articles/deploying-to-a-custom-rails-environment

**Comment by schneems** [comment]
Are you still seeing this issue? If you are, can you please provide me with an example app that demonstrates the problem https://www.codetriage.com/example_app. Let me know and I can re-open the issue.
