### ISSUE TITLE
Windows supported?

### ISSUE THREAD

**Issue by jchatel** [schneems/derailed_benchmarks#66]
I have Windows 7 64bits.

When I run: "bundle exec derailed bundle:mem"
or "bundle exec derailed bundle:mem development"

I the following printed over and over again (I suspect once per gem loaded?) and that's it. This seems to indicate that ps command requested is not supported on Windows? A message in the readme would be nice if this is the case.

Usage ps [-aefl] [-u uid]
-f = show process uids, ppids
-l = show process uids, ppids, pgids, winpids
-u uid = list processes owned by uid
-a, -e = show processes of all users
-s = show process summary
-W = show windows as well as cygwin processes

PS: gem 'stackprof' doesn't even compile on Windows.

**Comment by schneems** [comment]
This is due to https://github.com/schneems/get_process_mem/issues/15 please follow that issue, once I get a working gem on windows then you should be able to use derailed.

**Comment by jchatel** [comment]
Awesome, I'll follow up closely. Thanks

**Comment by schneems** [comment]
This was fixed in get_process_mem upgrade your gem to the latest
