### ISSUE TITLE
Could you include version requirements?

### ISSUE THREAD

**Issue by yakloinsteak** [schneems/derailed_benchmarks#7]
I could create a pull request to get this working in 1.9.3 with Rails 3.2, but in the meantime, could you provide the versions that are known to work with this gem? I really look forward to using this if I can get it running in our environment. Thanks for the work so far.

**Comment by melsatar** [comment]
So, does it support ruby 1.9.3 now ?

**Comment by schneems** [comment]
It may work on other versions of Ruby but i haven't tried. We don't officially support it, but i'm not intentionally excluding 1.9 folks. Btw 1.9 has been EOL for a LOOOOONG time, 2.0 will be EOL in February, upgrade your rubies.
