### ISSUE TITLE
derailed exec perf:em_over_time returns NoDatabaseError

### ISSUE THREAD

**Issue by bengalamx** [schneems/derailed_benchmarks#74]
I am trying to fix some memory leaks in my app, but when i do a `derailed exec perf:mem_over_time` it returns `ActiveRecord::NoDatabaseError (FATAL:  database "myapp_production" does not exist`.

What can i do to fix it?

**Comment by schneems** [comment]
You'll need to create the database. Follow directions here for guidelines of booting your app in production mode https://github.com/schneems/derailed_benchmarks#running-in-production-locally
