### ISSUE TITLE
Don't know how to build task 'perf:require_bench'

### ISSUE THREAD

**Issue by luiszacheu** [schneems/derailed_benchmarks#81]
I did the setup however when I run: 
$  rake -f perf.rake perf:require_bench
rake aborted!
Don't know how to build task 'perf:require_bench'
/Users/luiszacheu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/task_manager.rb:62:in `[]'
/Users/luiszacheu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:149:in `invoke_task'
/Users/luiszacheu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/luiszacheu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/luiszacheu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/luiszacheu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/luiszacheu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/luiszacheu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/luiszacheu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/luiszacheu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/luiszacheu/.rvm/rubies/ruby-2.2.4/bin/rake:33:in `<main>'

Returns this trace, do not understand what is happening can help me?
I'm using rails with activeadmin

thank you!

**Comment by schneems** [comment]
What does the contents of your `perf.rake` file look like?

**Comment by luiszacheu** [comment]
I using Devise and add a line to authenticate.
require 'bundler'
Bundler.setup

require 'derailed_benchmarks'
require 'derailed_benchmarks/tasks'

namespace :perf do
  task :rack_load do
    require ::File.expand_path('../config/environment',  __FILE__)
    DERAILED_APP = QprodeliveryWeb::Application
    DerailedBenchmarks.auth.user = -> { User.find_or_create!(email: "admin@teste.com) }
  end
end

**Comment by schneems** [comment]
What do you get when you run

```
$ rack -f perf.rake -T
```

**Comment by luiszacheu** [comment]
Well this command don't work for me, but the command below works:
`rack -f perf.rake -T` 
And get this:
`rake perf:allocated_objects  # outputs allocated object diff after app is called TEST_COUNT times
rake perf:gc                 # outputs GC::Profiler.report data while app is called TEST_COUNT times
rake perf:ips                # iterations per second
rake perf:mem                # show memory usage caused by invoking require per gem
rake perf:objects            # profiles ruby allocation
rake perf:ram_over_time      # outputs ram usage over time
rake perf:stackprof          # stackprof
rake perf:test               # hits the url TEST_COUNT times`

**Comment by luiszacheu** [comment]
I using Ruby 2.2.4 and Rails 4.2.5!

**Comment by schneems** [comment]
That was a typo, i meant `rake`

It doesn't look like you have `perf:require_bench`.

Also we don't list that as a command you can run https://github.com/schneems/derailed_benchmarks#running-derailed-exec

I think you want `perf:mem` or `bundle:mem`

**Comment by luiszacheu** [comment]
If i use `perf:men` works, but this command of Memory used at Require time how a know the total memory my application?

**Comment by luiszacheu** [comment]
Schneems works now, i remove the redirect if my application had to another page with Devise.
Please can you explain me, how difference when return:
TOP: 155.8789 MiB
  application: 73.2578 MiB
    activeadmin: 22.6484 MiB
      active_admin: 22.6406 MiB
        ransack: 15.7891 MiB
.....

The **TOP** is all memory that my application usage? Or the real value is **application**?

Thank you!

**Comment by schneems** [comment]
Top is everything.
