### ISSUE TITLE
Task 'setup' with USE_SERVER not failing with a 302 response

### ISSUE THREAD

**Issue by MatzFan** [schneems/derailed_benchmarks#85]
I've noticed that [this line](https://github.com/schneems/derailed_benchmarks/blob/master/lib/derailed_benchmarks/tasks.rb#L85) seems to ignore a 302 response - is this the desired behaviour? This happens, for example, when authentication fails with a controller redirect (am learning this the hard way trying to write custom AuthHelper for my Rack app). In this case I'm assuming the generated output is from the redirect path & not the intended PATH_TO_HIT. If so this seems misleading.

**Suggestion:**
Curl can [return response codes](https://superuser.com/a/442395), so could this be used to check for a 200 response - i.e. same logic as when USE_SERVER is not set?

**Comment by schneems** [comment]
If you blame that file you'll see some context around why the 302 exceptions were added. I'm happy to make the default behavior a bit more clear. I think maybe we should by default follow a 302 if that's not what we're already doing.

**Comment by MatzFan** [comment]
Thanks @schneems. Can't see a rationale for the difference in treatment of 302 response with & without server, looks like the difference was there from the [start](https://github.com/schneems/derailed_benchmarks/blob/2a10ead6307065674cee04b7bd82911c45e6d79a/lib/derailed_benchmarks/tasks.rb). Perhaps there is a good reason to follow a 302 response with a server & fail on a 302 without one, but I don't see it. No big deal anyway, please close the issue if this is desired behaviour.

**Comment by schneems** [comment]
Was probably a mistake that there's a difference. Most of derailed is hacked together based on immediate need.

**Comment by MatzFan** [comment]
Isn't everything?! Happy to do you a simple PR if you want a fail on anything except 200 for both scenarios.
