### ISSUE TITLE
PATH_TO_HIT shows error

### ISSUE THREAD

**Issue by vishnurkrishnan** [schneems/derailed_benchmarks#95]
Ruby 2.2.2 and Rails 3.2.22
I am following this link https://github.com/schneems/derailed_benchmarks, and running this server in production mode, when i was running this
PATH_TO_HIT=/setup_others/new_reason bundle exec derailed exec perf:mem

**Got this error**
Booting: production
Endpoint: "/setup_others/new_reason"
/Users/test/.rvm/gems/ruby-2.2.2/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:72: warning: already initialized constant DERAILED_APP
/Users/test/.rvm/gems/ruby-2.2.2/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:23: warning: previous definition of DERAILED_APP was here Impact of `require <file>` on RAM

Showing all `require <file>` calls that consume 0.3 MiB or more of RSS
Configure with `CUT_OFF=0` for all entries or `CUT_OFF=5` for few entries
Note: Files only count against RAM on their first load.
      If multiple libraries require the same file, then
       the 'cost' only shows up under the first library

/Users/test/.rvm/gems/ruby-2.2.2/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:92:in `call_app': Bad request: <html><body>You are being <a href="http://example.org/users/sign_in">redirected</a>.</body></html> (RuntimeError)

**Comment by benoittgt** [comment]
Did you try with full url like `PATH_TO_HIT='http://localhost:3000/users.json'` ?

If you are able to give me something to reproduce this issue I can have a look.
