### ISSUE TITLE
Is `task :foo` a relic from when the project was still in development?

### ISSUE THREAD

**Issue by NickLaMuro** [schneems/derailed_benchmarks#97]
Noticed this task while digging through the project (really cool stuff by the way!):

https://github.com/schneems/derailed_benchmarks/blob/2c6fb1d/lib/derailed_benchmarks/tasks.rb#L205-L232

Seems like it was added in your [second commit](https://github.com/schneems/derailed_benchmarks/commit/2a10ead6), modified to remove some noise in [the commit after](https://github.com/schneems/derailed_benchmarks/commit/45c18ba), but then really hasn't been touched since.  Also seems like it doesn't have any tests/documentation around it, and also isn't a terribly descriptive task name. 😉 

Just came across it while reading through the code base and was curious if it got left in by mistake.  Should be a simple exercise to remove it if that is the case, just didn't want to do it myself incase I was wrong about it's value (which happens... a lot).

**Comment by schneems** [comment]
Yup, that's basically what happened, cruft that I forgot about. Feel free to send me a PR to remove.
