### ISSUE TITLE
Detected parent died, dying

### ISSUE THREAD

**Issue by volkanunsal** [schneems/derailed_benchmarks#99]
I'm trying to use this gem with puma (3.8.1) web server , but anytime I run one of the tasks, the web server dies on me with this message. I don't know what might be happening. Has anyone seen this type of error before?

**Comment by schneems** [comment]
Nope, did you get it figured out?

**Comment by volkanunsal** [comment]
Apparently it's a standard server shutdown message. The benchmarks were run
successfully.
-- 
*Volkan Unsal*
*Product Engineer*
volkanunsal.com
